Repository SpineTracker60/back-end, pull requests merged in 2023-09, with the labels that each got.

#10 [Closes #1] Feat: Member 엔티티 생성
  src/main/java/com/spinetracker/spinetracker/domain/member/command/domain/aggregate/entity/Member.java
  src/main/java/com/spinetracker/spinetracker/domain/member/command/domain/aggregate/entity/enumtype/AgeRangeEnum.java
  src/main/java/com/spinetracker/spinetracker/domain/member/command/domain/aggregate/entity/enumtype/GenderEnum.java
  src/main/java/com/spinetracker/spinetracker/domain/member/command/domain/aggregate/entity/enumtype/PlatformEnum.java
  src/main/java/com/spinetracker/spinetracker/domain/member/command/domain/aggregate/entity/enumtype/RoleEnum.java
  src/main/java/com/spinetracker/spinetracker/domain/member/command/domain/aggregate/entity/vo/MemberInfoVO.java
Labels: ✨ Feature

#11 [Closes #9] Feat: TOKEN 엔티티 생성
  src/main/java/com/spinetracker/spinetracker/global/security/command/domain/aggregate/entity/Token.java
  src/main/java/com/spinetracker/spinetracker/global/security/command/domain/aggregate/vo/MemberVO.java
Labels: ✨ Feature

#13 [Closes #12] Feat : 깃허브 액션 설정
  .github/workflows/gradle-publish.yml
Labels: ✨ Feature, ⚙ Setting

#20 [Closes #18] Feat : 자세 로그 생성 어플리케이션 서비스 클래스 생성
  src/main/java/com/spinetracker/spinetracker/domain/posture/command/application/dto/CreatePostureDTO.java
  src/main/java/com/spinetracker/spinetracker/domain/posture/command/application/service/CreatePostureLogService.java
  src/main/java/com/spinetracker/spinetracker/domain/posture/command/domain/repository/PostureLogRepository.java
  src/test/java/com/spinetracker/spinetracker/domain/posture/command/application/service/CreatePostureLogServiceTest.java
Labels: ✨ Feature, ✅ Test

#21 [Closes #14] Feat: CREATE APPLICATION SERVICE 구현
  build.gradle
  src/main/java/com/spinetracker/spinetracker/domain/member/command/application/dto/CreateMemberByLocalDTO.java
  src/main/java/com/spinetracker/spinetracker/domain/member/command/application/dto/CreateMemberBySocialDTO.java
  src/main/java/com/spinetracker/spinetracker/domain/member/command/application/dto/UpdateMemberByLocalDTO.java
  src/main/java/com/spinetracker/spinetracker/domain/member/command/application/dto/UpdateMemberBySocialDTO.java
  src/main/java/com/spinetracker/spinetracker/domain/member/command/application/service/CreateMemberService.java
  src/main/java/com/spinetracker/spinetracker/domain/member/command/application/service/UpdateMemberService.java
  src/main/java/com/spinetracker/spinetracker/domain/member/command/domain/aggregate/entity/Member.java
  src/main/java/com/spinetracker/spinetracker/domain/member/command/domain/repository/MemberRepository.java
  src/test/java/com/spinetracker/spinetracker/domain/member/command/application/service/CreateMemberServiceTest.java
Labels: ✨ Feature, ✅ Test

#24 [#23] Feat : SECURITY CONFIGURATION 구현 중
  build.gradle
  src/main/java/com/spinetracker/spinetracker/SpineTrackerApplication.java
  src/main/java/com/spinetracker/spinetracker/domain/member/command/application/dto/CreateMemberByLocalDTO.java
  src/main/java/com/spinetracker/spinetracker/domain/member/command/application/dto/CreateMemberDTO.java
  src/main/java/com/spinetracker/spinetracker/domain/member/command/application/dto/UpdateMemberByLocalDTO.java
  src/main/java/com/spinetracker/spinetracker/domain/member/command/application/dto/UpdateMemberBySocialDTO.java
  src/main/java/com/spinetracker/spinetracker/domain/member/command/application/dto/UpdateMemberDTO.java
  src/main/java/com/spinetracker/spinetracker/domain/member/command/application/service/CreateMemberService.java
  src/main/java/com/spinetracker/spinetracker/domain/member/command/application/service/UpdateMemberService.java
  src/main/java/com/spinetracker/spinetracker/domain/member/command/domain/aggregate/entity/Member.java
  src/main/java/com/spinetracker/spinetracker/domain/member/query/application/dto/FindMemberDTO.java
  src/main/java/com/spinetracker/spinetracker/domain/member/query/application/service/FindMemberService.java
  src/main/java/com/spinetracker/spinetracker/domain/member/query/domain/repository/MemberMapper.java
  src/main/java/com/spinetracker/spinetracker/global/configuration/AppProperties.java
  src/main/java/com/spinetracker/spinetracker/global/configuration/SecurityConfiguration.java
  src/main/java/com/spinetracker/spinetracker/global/exception/UserNotFoundException.java
  src/main/java/com/spinetracker/spinetracker/global/exception/exception.md
  src/main/java/com/spinetracker/spinetracker/global/filter/filer.md
  src/main/java/com/spinetracker/spinetracker/global/security/command/application/service/CustomOAuth2UserService.java
  src/main/java/com/spinetracker/spinetracker/global/security/command/application/service/CustomUserDetailService.java
  src/main/java/com/spinetracker/spinetracker/global/security/command/domain/aggregate/util/CookieUtils.java
  src/main/java/com/spinetracker/spinetracker/global/security/command/domain/provider/Google.java
  src/main/java/com/spinetracker/spinetracker/global/security/command/domain/provider/OAuth2UserInfo.java
  src/main/java/com/spinetracker/spinetracker/global/security/command/domain/provider/OAuth2UserInfoFactory.java
  src/main/java/com/spinetracker/spinetracker/global/security/token/UserPrincipal.java
  src/main/resources/mapper/member/MemberMapper.xml
  src/test/java/com/spinetracker/spinetracker/domain/member/command/application/service/CreateMemberServiceTest.java
  src/test/java/com/spinetracker/spinetracker/domain/member/command/application/service/UpdateMemberServiceTest.java
Labels: ✨ Feature

#31 [Closes #29] Feat : SECURITY 카카오 로그인 구현
  src/main/java/com/spinetracker/spinetracker/domain/member/command/domain/aggregate/entity/enumtype/PlatformEnum.java
  src/main/java/com/spinetracker/spinetracker/global/security/command/application/service/CustomOAuth2UserService.java
  src/main/java/com/spinetracker/spinetracker/global/security/command/domain/provider/Kakao.java
  src/main/java/com/spinetracker/spinetracker/global/security/command/domain/provider/OAuth2UserInfoFactory.java
Labels: ✨ Feature

#34 [Closes #32] Feat : SECURITY 단위 테스트 구현
  src/main/java/com/spinetracker/spinetracker/domain/member/query/application/service/FindMemberService.java
  src/main/java/com/spinetracker/spinetracker/domain/member/query/domain/repository/MemberMapper.java
  src/main/java/com/spinetracker/spinetracker/global/security/command/application/service/CustomOAuth2UserService.java
  src/main/resources/mapper/member/MemberMapper.xml
  src/test/java/com/spinetracker/spinetracker/domain/member/query/application/service/FindMemberServiceTest.java
  src/test/java/com/spinetracker/spinetracker/global/filter/TokenAuthenticationFilterTest.java
  src/test/java/com/spinetracker/spinetracker/global/security/command/application/service/IssueTokenServiceTest.java
  src/test/java/com/spinetracker/spinetracker/global/security/command/domain/service/CustomTokenServiceTest.java
Labels: 🏗️ Refactoring, ✅ Test

#40 [Closes #36] Feat : MEMBERINFO 엔티티 생성 및 CREATE APPLICATION SERVICE 구현
  src/main/java/com/spinetracker/spinetracker/domain/member/command/application/dto/CreateMemberDTO.java
  src/main/java/com/spinetracker/spinetracker/domain/member/command/application/dto/MemberInfoDTO.java
  src/main/java/com/spinetracker/spinetracker/domain/member/command/application/service/CreateMemberInfoService.java
  src/main/java/com/spinetracker/spinetracker/domain/member/command/application/service/CreateMemberService.java
  src/main/java/com/spinetracker/spinetracker/domain/member/command/domain/aggregate/entity/Member.java
  src/main/java/com/spinetracker/spinetracker/domain/member/command/domain/aggregate/entity/MemberInfo.java
  src/main/java/com/spinetracker/spinetracker/domain/member/command/domain/aggregate/entity/enumtype/AgeRangeEnum.java
  src/main/java/com/spinetracker/spinetracker/domain/member/command/domain/aggregate/entity/vo/AgeRangeVO.java
  src/main/java/com/spinetracker/spinetracker/domain/member/command/domain/aggregate/entity/vo/MemberInfoVO.java
  src/main/java/com/spinetracker/spinetracker/domain/member/command/domain/aggregate/entity/vo/MemberVO.java
  src/main/java/com/spinetracker/spinetracker/domain/member/command/domain/repository/MemberInfoRepository.java
  src/main/java/com/spinetracker/spinetracker/domain/member/query/application/dto/FindMemberDTO.java
  src/test/java/com/spinetracker/spinetracker/domain/member/command/application/service/CreateMemberInfoServiceTest.java
Labels: ✨ Feature, ✅ Test

#38 [Closes #30] Feat : 사용자 생성 시 채팅방 생성 구현
  build.gradle
  src/main/java/com/spinetracker/spinetracker/domain/chatroom/command/application/dto/FindChatroomDTO.java
  src/main/java/com/spinetracker/spinetracker/domain/chatroom/command/application/service/RequestChatroomService.java
  src/main/java/com/spinetracker/spinetracker/domain/chatroom/command/domain/service/RequestChatroom.java
  src/main/java/com/spinetracker/spinetracker/domain/chatroom/command/infra/RequestChatroomImpl.java
  src/main/java/com/spinetracker/spinetracker/domain/chatroom/command/infra/response/ChatRoomBody.java
  src/main/java/com/spinetracker/spinetracker/domain/chatroom/command/infra/response/ChatRoomResponse.java
  src/main/java/com/spinetracker/spinetracker/domain/chatroom/command/infra/response/Response.java
  src/main/java/com/spinetracker/spinetracker/domain/member/command/application/service/CreateMemberService.java
  src/test/java/com/spinetracker/spinetracker/domain/chatroom/command/application/service/RequestChatroomServiceTest.java
Labels: ✨ Feature, ✅ Test

#46 [Closes #42] Feat : MemberInfo CREATE, UPDATE CONTROLLER 구현
  src/main/java/com/spinetracker/spinetracker/domain/member/command/application/controller/MemberInfoController.java
  src/main/java/com/spinetracker/spinetracker/global/common/response/ResponseDTO.java
Labels: ✨ Feature

#50 [#closes 45] : Feat : 자세 로그 저장 Controller 구현
  src/main/java/com/spinetracker/spinetracker/domain/chatroom/command/infra/RequestChatroomImpl.java
  src/main/java/com/spinetracker/spinetracker/domain/posture/command/application/controller/CreatePostureController.java
  src/main/java/com/spinetracker/spinetracker/domain/posture/command/application/dto/CreatePostureDTO.java
  src/main/java/com/spinetracker/spinetracker/domain/posture/command/application/dto/CreatePostureLogDTO.java
  src/main/java/com/spinetracker/spinetracker/domain/posture/command/application/dto/PostureBody.java
  src/main/java/com/spinetracker/spinetracker/domain/posture/command/application/dto/ResponsePosture.java
  src/main/java/com/spinetracker/spinetracker/domain/posture/command/application/service/CreatePostureLogService.java
  src/main/java/com/spinetracker/spinetracker/global/configuration/JacksonConfiguration.java
  src/test/java/com/spinetracker/spinetracker/domain/chatroom/command/application/service/RequestChatroomServiceTest.java
  src/test/java/com/spinetracker/spinetracker/domain/posture/command/application/controller/CreatePostureControllerTest.java
  src/test/java/com/spinetracker/spinetracker/domain/posture/command/application/service/CreatePostureLogServiceTest.java
Labels: ✨ Feature, ✅ Test

#52 [#closes 51] : Refactor : 임시 채팅방 요청 테스트 주석 처리
  src/main/java/com/spinetracker/spinetracker/domain/posture/command/application/controller/CreatePostureController.java
  src/main/java/com/spinetracker/spinetracker/domain/posture/command/application/service/CreatePostureLogService.java
  src/test/java/com/spinetracker/spinetracker/domain/chatroom/command/application/service/RequestChatroomServiceTest.java
  src/test/java/com/spinetracker/spinetracker/domain/posture/command/application/service/CreatePostureLogServiceTest.java
Labels: 🏗️ Refactoring, ✅ Test

#57 [Closes #56] FEAT : MEMBER 관련 CONTROLLER TEST 완료
  src/main/java/com/spinetracker/spinetracker/domain/member/command/application/controller/MemberController.java
  src/main/java/com/spinetracker/spinetracker/domain/member/command/application/controller/MemberInfoController.java
  src/main/java/com/spinetracker/spinetracker/domain/member/command/application/dto/MemberInfoDTO.java
  src/test/java/com/spinetracker/spinetracker/domain/member/command/application/controller/MemberControllerTest.java
  src/test/java/com/spinetracker/spinetracker/domain/member/command/application/controller/MemberInfoControllerTest.java
  src/test/java/com/spinetracker/spinetracker/global/common/WithMockCustomUser.java
  src/test/java/com/spinetracker/spinetracker/global/common/WithMockCustomUserSecurityContextFactory.java
Labels: ✅ Test

#58 [#closes 53] : Feat : springdoc을 통한 Swagger 3.0 연결
  build.gradle
  src/main/java/com/spinetracker/spinetracker/domain/posture/command/application/controller/CreatePostureController.java
  src/main/java/com/spinetracker/spinetracker/domain/posture/command/application/dto/CreatePostureLogDTO.java
  src/main/java/com/spinetracker/spinetracker/domain/posture/command/application/dto/PostureBody.java
  src/main/java/com/spinetracker/spinetracker/global/configuration/SecurityConfiguration.java
  src/main/java/com/spinetracker/spinetracker/global/configuration/SwaggerConfiguration.java
  src/main/java/com/spinetracker/spinetracker/global/docs/controller/SwaggerRedirector.java
Labels: 📃 Docs, ✨ Feature, ⚙ Setting

#61 [Closes #55] FEAT : BOARD CREATE APPLICATION SERVICE 구현
  src/main/java/com/spinetracker/spinetracker/domain/board/command/application/dto/BoardDTO.java
  src/main/java/com/spinetracker/spinetracker/domain/board/command/application/service/CreateBoardService.java
  src/main/java/com/spinetracker/spinetracker/domain/board/command/domain/aggregate/entity/Board.java
  src/main/java/com/spinetracker/spinetracker/domain/board/command/domain/repository/BoardRepository.java
  src/test/java/com/spinetracker/spinetracker/domain/board/command/application/service/CreateBoardServiceTest.java
Labels: ✨ Feature, ✅ Test

#62 [Closes #59] : Feat : 오늘의 자세 기록에 대한 Summary 조회 기능 구현
  src/main/java/com/spinetracker/spinetracker/domain/posture/query/application/controller/FindDailyPostureController.java
  src/main/java/com/spinetracker/spinetracker/domain/posture/query/application/dto/DailyPostureLogDTO.java
  src/main/java/com/spinetracker/spinetracker/domain/posture/query/application/dto/FindPostureLogDTO.java
  src/main/java/com/spinetracker/spinetracker/domain/posture/query/application/service/FindDailyPostureLogService.java
  src/main/java/com/spinetracker/spinetracker/domain/posture/query/application/service/FindPostureLogService.java
  src/main/java/com/spinetracker/spinetracker/domain/posture/query/domain/repository/PostureLogMapper.java
  src/main/java/com/spinetracker/spinetracker/domain/posture/query/domain/service/CalcDailyPostureLogService.java
  src/main/java/com/spinetracker/spinetracker/global/configuration/SwaggerConfiguration.java
  src/main/resources/mapper/postureLog/PostureLogMapper.xml
  src/test/java/com/spinetracker/spinetracker/domain/posture/query/application/service/FindDailyPostureLogServiceTest.java
Labels: 📃 Docs, ✨ Feature, ✅ Test

#64 [Closes #63] FEAT : MEMBER 사용자 추가 정보 입력 확인 구현
  src/main/java/com/spinetracker/spinetracker/domain/member/command/application/controller/MemberInfoController.java
  src/main/java/com/spinetracker/spinetracker/domain/member/command/application/dto/MemberInfoDTO.java
  src/main/java/com/spinetracker/spinetracker/domain/member/query/application/controller/FindMemberInfoController.java
  src/main/java/com/spinetracker/spinetracker/domain/member/query/application/service/FindMemberService.java
  src/main/java/com/spinetracker/spinetracker/domain/member/query/domain/repository/MemberInfoMapper.java
  src/main/resources/mapper/member/MemberInfoMapper.xml
  src/main/resources/mapper/member/MemberMapper.xml
  src/test/java/com/spinetracker/spinetracker/domain/member/command/application/controller/MemberInfoControllerTest.java
  src/test/java/com/spinetracker/spinetracker/domain/member/command/application/service/CreateMemberInfoServiceTest.java
  src/test/java/com/spinetracker/spinetracker/domain/member/command/application/service/DeleteMemberServiceTest.java
  src/test/java/com/spinetracker/spinetracker/domain/member/command/application/service/UpdateMemberInfoServiceTest.java
  src/test/java/com/spinetracker/spinetracker/domain/member/query/application/controller/FindMemberInfoControllerTest.java
  src/test/java/com/spinetracker/spinetracker/domain/member/query/application/service/FindMemberServiceTest.java
Labels: ✨ Feature, ✅ Test

#66 [Closes #60] : Feat : 주간 자세 기록 대시보드 조회 구현
  src/main/java/com/spinetracker/spinetracker/domain/posture/query/application/controller/FindWeeklyPostureController.java
  src/main/java/com/spinetracker/spinetracker/domain/posture/query/application/dto/WeeklyDashBoardPostureLogDTO.java
  src/main/java/com/spinetracker/spinetracker/domain/posture/query/application/service/DashboardPostureLogService.java
  src/main/java/com/spinetracker/spinetracker/domain/posture/query/application/service/FindPostureLogService.java
  src/main/java/com/spinetracker/spinetracker/domain/posture/query/domain/PostureTimePerDate.java
  src/main/java/com/spinetracker/spinetracker/domain/posture/query/domain/repository/PostureLogMapper.java
  src/main/java/com/spinetracker/spinetracker/domain/posture/query/domain/service/CalcDashboardPostureLogService.java
  src/main/resources/mapper/postureLog/PostureLogMapper.xml
  src/test/java/com/spinetracker/spinetracker/domain/posture/query/application/service/DashboardPostureLogServiceTest.java
Labels: 📃 Docs, ✨ Feature, ✅ Test

#69 [Closes #68] FEAT : MEMBERINFO Swagger 설정
  src/main/java/com/spinetracker/spinetracker/domain/member/command/application/dto/CheckMemberInfoAddedDTO.java
  src/main/java/com/spinetracker/spinetracker/domain/member/command/application/dto/MemberInfoDTO.java
  src/main/java/com/spinetracker/spinetracker/domain/member/query/application/controller/FindMemberInfoController.java
Labels: 📃 Docs, ✨ Feature

#70 Hotfix/memberinfo 68 memberinfodto update
  src/main/java/com/spinetracker/spinetracker/domain/board/command/application/service/UpdateBoardService.java
  src/main/java/com/spinetracker/spinetracker/domain/member/command/application/controller/MemberInfoController.java
  src/main/java/com/spinetracker/spinetracker/domain/member/command/application/dto/CreateMemberInfoDTO.java
  src/main/java/com/spinetracker/spinetracker/domain/member/command/application/dto/FindMemberInfoDTO.java
  src/main/java/com/spinetracker/spinetracker/domain/member/command/application/service/CreateMemberInfoService.java
  src/main/java/com/spinetracker/spinetracker/domain/member/command/application/service/UpdateMemberInfoService.java
  src/main/java/com/spinetracker/spinetracker/domain/member/command/domain/aggregate/entity/MemberInfo.java
  src/main/java/com/spinetracker/spinetracker/domain/member/command/infra/GoogleUnlinkResponse.java
  src/main/java/com/spinetracker/spinetracker/domain/member/command/infra/service/UnlinkGoogle.java
  src/main/java/com/spinetracker/spinetracker/domain/member/query/application/controller/FindMemberInfoController.java
  src/main/java/com/spinetracker/spinetracker/global/security/command/application/service/CustomOAuth2UserService.java
  src/main/resources/mapper/member/MemberInfoMapper.xml
  src/main/resources/mapper/member/MemberMapper.xml
  src/test/java/com/spinetracker/spinetracker/domain/member/command/application/controller/MemberInfoControllerTest.java
  src/test/java/com/spinetracker/spinetracker/domain/member/command/application/service/CreateMemberInfoServiceTest.java
  src/test/java/com/spinetracker/spinetracker/domain/member/command/application/service/UpdateMemberInfoServiceTest.java
  src/test/java/com/spinetracker/spinetracker/domain/member/query/application/service/FindMemberServiceTest.java
Labels: 🏗️ Refactoring

#73 [Closes #71] FEAT : createMemberInfo Swagger 설정
  src/main/java/com/spinetracker/spinetracker/domain/member/command/application/controller/MemberInfoController.java
  src/main/java/com/spinetracker/spinetracker/domain/member/command/application/dto/CreateMemberInfoDTO.java
  src/main/java/com/spinetracker/spinetracker/domain/member/command/domain/aggregate/entity/enumtype/GenderEnum.java
Labels: 📃 Docs, 🏗️ Refactoring

#75 [Closes #67] : Feat : 주간 불안정 자세 비율 계산 조회 구현
  src/main/java/com/spinetracker/spinetracker/domain/posture/query/application/controller/FindUnStableRatioPostureController.java
  src/main/java/com/spinetracker/spinetracker/domain/posture/query/application/dto/UnStableRatioDTO.java
  src/main/java/com/spinetracker/spinetracker/domain/posture/query/application/service/FindUnstableRatioPostureLogService.java
  src/main/java/com/spinetracker/spinetracker/domain/posture/query/domain/PostureTimePerDate.java
  src/main/java/com/spinetracker/spinetracker/domain/posture/query/domain/service/CalcUnStableRatioPostureLogService.java
  src/main/java/com/spinetracker/spinetracker/global/configuration/SecurityConfiguration.java
Labels: 📃 Docs, ✨ Feature

#76 [Closes #72] FEAT : 현재 로그인 되어 있는 유저 정보를 가져오는 API 구현
  src/main/java/com/spinetracker/spinetracker/domain/member/command/application/dto/CreatedMemberInfoResponseDTO.java
  src/main/java/com/spinetracker/spinetracker/domain/member/query/application/controller/FindMemberInfoController.java
  src/main/java/com/spinetracker/spinetracker/domain/member/query/application/dto/FindMemberDTO.java
  src/main/java/com/spinetracker/spinetracker/domain/member/query/application/service/FindMemberService.java
  src/main/resources/mapper/member/MemberMapper.xml
  src/test/java/com/spinetracker/spinetracker/domain/member/command/application/controller/MemberInfoControllerTest.java
  src/test/java/com/spinetracker/spinetracker/domain/posture/command/application/controller/CreatePostureControllerTest.java
  src/test/java/com/spinetracker/spinetracker/global/common/WithMockCustomUserSecurityContextFactory.java
  src/test/java/com/spinetracker/spinetracker/global/security/command/application/controller/AuthControllerTest.java
Labels: 📃 Docs, ✨ Feature, 🏗️ Refactoring, ✅ Test

#78 [Closes #77] FEAT : 사용자 추가 정보 조회 API 구현
  src/main/java/com/spinetracker/spinetracker/domain/member/command/application/dto/FindMemberInfoDTO.java
  src/main/java/com/spinetracker/spinetracker/domain/member/query/application/controller/FindMemberInfoController.java
  src/main/java/com/spinetracker/spinetracker/domain/member/query/application/service/FindMemberService.java
  src/main/java/com/spinetracker/spinetracker/domain/member/query/domain/repository/MemberInfoMapper.java
  src/main/resources/mapper/member/MemberInfoMapper.xml
Labels: 📃 Docs, ✨ Feature

#85 [Closes #84] FEAT : BOARD READ APPLICATION SERVICE 구현
  src/main/java/com/spinetracker/spinetracker/domain/board/command/application/dto/FindBoardDTO.java
  src/main/java/com/spinetracker/spinetracker/domain/board/query/application/service/FindBoardService.java
  src/main/java/com/spinetracker/spinetracker/domain/board/query/domain/repository/BoardMapper.java
  src/main/java/com/spinetracker/spinetracker/global/configuration/SecurityConfiguration.java
  src/main/resources/mapper/board/BoardMapper.xml
  src/test/java/com/spinetracker/spinetracker/domain/board/query/application/service/FindBoardServiceTest.java
Labels: ✨ Feature, ✅ Test

#89 [Closes #86] Refactoring : PRODUCT 엔티티 생성 및 READ, CREATE SERVICE 수정
  src/main/java/com/spinetracker/spinetracker/domain/board/command/application/dto/BoardDTO.java
  src/main/java/com/spinetracker/spinetracker/domain/board/command/application/dto/CreatePostDTO.java
  src/main/java/com/spinetracker/spinetracker/domain/board/command/application/dto/FindBoardDTO.java
  src/main/java/com/spinetracker/spinetracker/domain/board/command/application/dto/UpdatePostDTO.java
  src/main/java/com/spinetracker/spinetracker/domain/board/command/application/service/CreateBoardService.java
  src/main/java/com/spinetracker/spinetracker/domain/board/command/application/service/DeleteBoardService.java
  src/main/java/com/spinetracker/spinetracker/domain/board/command/application/service/UpdateBoardService.java
  src/main/java/com/spinetracker/spinetracker/domain/board/command/domain/aggregate/entity/Board.java
  src/main/java/com/spinetracker/spinetracker/domain/board/command/domain/aggregate/entity/Product.java
  src/main/java/com/spinetracker/spinetracker/domain/board/command/domain/aggregate/entity/vo/ProductVO.java
  src/main/java/com/spinetracker/spinetracker/domain/board/command/domain/repository/ProductRepository.java
  src/main/java/com/spinetracker/spinetracker/domain/board/query/application/dto/FindBoardDTO.java
  src/main/java/com/spinetracker/spinetracker/domain/board/query/application/dto/FindPostDTO.java
  src/main/java/com/spinetracker/spinetracker/domain/board/query/application/dto/FindProductDTO.java
  src/main/java/com/spinetracker/spinetracker/domain/board/query/application/service/FindBoardService.java
  src/main/java/com/spinetracker/spinetracker/domain/board/query/application/service/FindProductService.java
  src/main/java/com/spinetracker/spinetracker/domain/board/query/domain/repository/BoardMapper.java
  src/main/java/com/spinetracker/spinetracker/domain/board/query/domain/repository/ProductMapper.java
  src/main/resources/mapper/board/BoardMapper.xml
  src/main/resources/mapper/board/ProductMapper.xml
  src/test/java/com/spinetracker/spinetracker/domain/board/command/application/service/CreateBoardServiceTest.java
  src/test/java/com/spinetracker/spinetracker/domain/board/command/application/service/DeleteBoardServiceTest.java
  src/test/java/com/spinetracker/spinetracker/domain/board/command/application/service/UpdateBoardServiceTest.java
  src/test/java/com/spinetracker/spinetracker/domain/board/query/application/service/FindBoardServiceTest.java
Labels: ✨ Feature, 🏗️ Refactoring

#93 [Closes #90] Feat : BOARD 게시글 전체 조회 CONTROLLER 구현
  src/main/java/com/spinetracker/spinetracker/domain/board/command/domain/aggregate/entity/Board.java
  src/main/java/com/spinetracker/spinetracker/domain/board/query/application/controller/FindBoardController.java
  src/main/java/com/spinetracker/spinetracker/domain/board/query/application/dto/FindBoardDTO.java
  src/main/java/com/spinetracker/spinetracker/domain/board/query/application/dto/FindPostDTO.java
  src/main/java/com/spinetracker/spinetracker/domain/board/query/application/service/FindBoardService.java
  src/main/java/com/spinetracker/spinetracker/domain/member/command/application/controller/MemberInfoController.java
  src/main/java/com/spinetracker/spinetracker/domain/member/query/application/controller/FindMemberInfoController.java
  src/main/java/com/spinetracker/spinetracker/global/configuration/SecurityConfiguration.java
  src/test/java/com/spinetracker/spinetracker/domain/board/command/application/service/CreateBoardServiceTest.java
  src/test/java/com/spinetracker/spinetracker/domain/board/query/application/service/FindBoardServiceTest.java
Labels: ✨ Feature

#88 [#87] Feat : FCM 환경 설정
  .github/workflows/gradle-publish.yml
  .gitignore
  build.gradle
  src/main/java/com/spinetracker/spinetracker/global/configuration/FCMConfiguration.java
  src/main/java/com/spinetracker/spinetracker/infra/firebase/application/service/CreateFcmTokenService.java
  src/main/java/com/spinetracker/spinetracker/infra/firebase/application/service/UpdateFcmTokenService.java
  src/main/java/com/spinetracker/spinetracker/infra/firebase/domain/entity/FCMToken.java
  src/main/java/com/spinetracker/spinetracker/infra/firebase/domain/entity/vo/MemberVO.java
  src/main/java/com/spinetracker/spinetracker/infra/firebase/domain/repository/FcmTokenRepository.java
  src/main/java/com/spinetracker/spinetracker/infra/firebase/infra/service/GetAccessTokenService.java
  src/main/java/com/spinetracker/spinetracker/infra/firebase/infra/service/PostMessageService.java
Labels: ✨ Feature, ⚙ Setting

#96 [Closes #94] Feat : BOARD 게시글 생성 CONTROLLER 구현
  src/main/java/com/spinetracker/spinetracker/domain/board/command/application/controller/BoardController.java
  src/main/java/com/spinetracker/spinetracker/domain/board/command/application/dto/CreatePostDTO.java
  src/main/java/com/spinetracker/spinetracker/domain/board/command/application/dto/CreatedBoardResponseDTO.java
  src/main/java/com/spinetracker/spinetracker/domain/board/query/application/controller/FindBoardController.java
Labels: 📃 Docs, ✨ Feature

#98 [Closes #95] Feat : FCM 토큰 생성 및 업데이트 컨트롤러 생성
  src/main/java/com/spinetracker/spinetracker/infra/firebase/command/application/controller/CreateFcmTokenController.java
  src/main/java/com/spinetracker/spinetracker/infra/firebase/command/application/controller/UpdateFcmTokenController.java
  src/main/java/com/spinetracker/spinetracker/infra/firebase/command/application/dto/CreateFcmTokenDTO.java
  src/main/java/com/spinetracker/spinetracker/infra/firebase/command/application/dto/ResponseFcmToken.java
  src/main/java/com/spinetracker/spinetracker/infra/firebase/command/application/service/CreateFcmTokenService.java
  src/main/java/com/spinetracker/spinetracker/infra/firebase/command/application/service/UpdateFcmTokenService.java
  src/main/java/com/spinetracker/spinetracker/infra/firebase/command/domain/entity/FCMToken.java
  src/main/java/com/spinetracker/spinetracker/infra/firebase/command/domain/entity/vo/MemberVO.java
  src/main/java/com/spinetracker/spinetracker/infra/firebase/command/domain/repository/FcmTokenRepository.java
  src/main/java/com/spinetracker/spinetracker/infra/firebase/command/infra/service/GetAccessTokenService.java
  src/main/java/com/spinetracker/spinetracker/infra/firebase/command/infra/service/PostMessageService.java
Labels: 📃 Docs, ✨ Feature

#100 [Closes #97] Feat : BOARD 게시글 수정 CONTROLLER 구현
  src/main/java/com/spinetracker/spinetracker/domain/board/command/application/controller/BoardController.java
  src/main/java/com/spinetracker/spinetracker/domain/board/command/application/dto/UpdatePostDTO.java
  src/main/java/com/spinetracker/spinetracker/domain/board/command/application/service/UpdateBoardService.java
  src/main/java/com/spinetracker/spinetracker/domain/member/command/application/dto/CheckMemberInfoAddedDTO.java
  src/main/java/com/spinetracker/spinetracker/domain/member/command/application/dto/CreatedMemberInfoResponseDTO.java
  src/test/java/com/spinetracker/spinetracker/domain/board/command/application/service/UpdateBoardServiceTest.java
Labels: 📃 Docs, ✨ Feature

#104 [Closes #99] Feat :FCM 토큰FindController 구현
  .github/workflows/gradle-publish.yml
  src/main/java/com/spinetracker/spinetracker/domain/posture/command/application/controller/CreatePostureController.java
  src/main/java/com/spinetracker/spinetracker/domain/posture/command/application/dto/CreatePostureLogDTO.java
  src/main/java/com/spinetracker/spinetracker/domain/posture/command/application/service/CreatePostureLogService.java
  src/main/java/com/spinetracker/spinetracker/domain/posture/command/application/service/PostPostureLogMessageService.java
  src/main/java/com/spinetracker/spinetracker/domain/posture/command/domain/service/RequestPostFcmMessage.java
  src/main/java/com/spinetracker/spinetracker/domain/posture/command/infra/service/RequestPostFcmMessageImpl.java
  src/main/java/com/spinetracker/spinetracker/global/configuration/SecurityConfiguration.java
  src/main/java/com/spinetracker/spinetracker/infra/firebase/command/application/dto/ResponseFcmToken.java
  src/main/java/com/spinetracker/spinetracker/infra/firebase/command/infra/service/PostMessageService.java
  src/main/java/com/spinetracker/spinetracker/infra/firebase/query/application/controller/FindFcmTokenController.java
  src/main/java/com/spinetracker/spinetracker/infra/firebase/query/application/dto/FindFcmTokenDTO.java
  src/main/java/com/spinetracker/spinetracker/infra/firebase/query/application/service/FindFcmTokenService.java
  src/main/java/com/spinetracker/spinetracker/infra/firebase/query/domain/repository/FcmTokenMapper.java
  src/main/resources/mapper/fcmToken/FcmTokenMapper.xml
  src/test/java/com/spinetracker/spinetracker/domain/posture/command/application/controller/CreatePostureControllerTest.java
Labels: 📬 API, 📃 Docs, ✨ Feature

#105 [Closes #103] Feat : PRODUCT 상품 조회 CONTROLLER 구현
  src/main/java/com/spinetracker/spinetracker/domain/board/query/application/controller/FindProductController.java
  src/main/java/com/spinetracker/spinetracker/domain/board/query/application/dto/FindProductDTO.java
  src/main/resources/mapper/board/ProductMapper.xml
Labels: 📃 Docs, ✨ Feature

#107 [Closes #106] Refactoring : 상품 생성 CREATE APPLICATION SERVICE 구현
  src/main/java/com/spinetracker/spinetracker/domain/board/command/application/dto/CreateProductDTO.java
  src/main/java/com/spinetracker/spinetracker/domain/board/command/application/service/CreateBoardService.java
  src/test/java/com/spinetracker/spinetracker/domain/board/command/application/service/CreateBoardServiceTest.java
Labels: 🏗️ Refactoring

#110 [Closes #109] Refactor : FCM 클라이언트 연결 리팩토링
  src/main/java/com/spinetracker/spinetracker/domain/posture/command/application/service/PostPostureLogMessageService.java
  src/main/java/com/spinetracker/spinetracker/infra/firebase/command/application/dto/ResponseFcmToken.java
  src/main/java/com/spinetracker/spinetracker/infra/firebase/command/infra/service/PostMessageService.java
  src/main/java/com/spinetracker/spinetracker/infra/firebase/query/application/controller/FindFcmTokenController.java
Labels: 📬 API, 🏗️ Refactoring

#111 [Closes #108] Refactoring : 상품 생성 및 게시글 조회 refactoring
  build.gradle
  src/main/java/com/spinetracker/spinetracker/domain/board/command/application/controller/ProductController.java
  src/main/java/com/spinetracker/spinetracker/domain/board/command/application/dto/CreatePostDTO.java
  src/main/java/com/spinetracker/spinetracker/domain/board/command/application/dto/ProductUrlRequestDTO.java
  src/main/java/com/spinetracker/spinetracker/domain/board/command/application/service/CreateBoardService.java
  src/main/java/com/spinetracker/spinetracker/domain/board/command/domain/aggregate/lib/MetaElement.java
  src/main/java/com/spinetracker/spinetracker/domain/board/command/domain/aggregate/lib/OpenGraph.java
  src/main/java/com/spinetracker/spinetracker/domain/board/command/domain/aggregate/lib/OpenGraphNamespace.java
  src/main/java/com/spinetracker/spinetracker/domain/board/query/application/dto/FindBoardDTO.java
  src/main/java/com/spinetracker/spinetracker/domain/board/query/application/service/FindBoardService.java
  src/main/java/com/spinetracker/spinetracker/global/configuration/SecurityConfiguration.java
  src/test/java/com/spinetracker/spinetracker/domain/board/command/application/service/CreateBoardServiceTest.java
  src/test/java/com/spinetracker/spinetracker/domain/board/command/application/service/DeleteBoardServiceTest.java
Labels: 📃 Docs, 🏗️ Refactoring

#112 [Closes #108] Refactoring : 상품 생성 및 게시글 조회 refactoring
  build.gradle
  src/main/java/com/spinetracker/spinetracker/domain/board/command/application/controller/ProductController.java
  src/main/java/com/spinetracker/spinetracker/domain/board/command/application/dto/CreatePostDTO.java
  src/main/java/com/spinetracker/spinetracker/domain/board/command/application/dto/ProductUrlRequestDTO.java
  src/main/java/com/spinetracker/spinetracker/domain/board/command/application/dto/ProductUrlResponseDTO.java
  src/main/java/com/spinetracker/spinetracker/domain/board/command/application/service/CreateBoardService.java
  src/main/java/com/spinetracker/spinetracker/domain/board/command/domain/aggregate/lib/MetaElement.java
  src/main/java/com/spinetracker/spinetracker/domain/board/command/domain/aggregate/lib/OpenGraph.java
  src/main/java/com/spinetracker/spinetracker/domain/board/command/domain/aggregate/lib/OpenGraphNamespace.java
  src/main/java/com/spinetracker/spinetracker/domain/board/command/domain/service/RequestProductInfo.java
  src/main/java/com/spinetracker/spinetracker/domain/board/command/infra/response/CoupangOpenGraphResponse.java
  src/main/java/com/spinetracker/spinetracker/domain/board/command/infra/service/RequestProductInfoImpl.java
  src/main/java/com/spinetracker/spinetracker/domain/board/query/application/dto/FindBoardDTO.java
  src/main/java/com/spinetracker/spinetracker/domain/board/query/application/service/FindBoardService.java
  src/test/java/com/spinetracker/spinetracker/domain/board/command/application/service/CreateBoardServiceTest.java
  src/test/java/com/spinetracker/spinetracker/domain/board/command/application/service/DeleteBoardServiceTest.java
  src/test/java/com/spinetracker/spinetracker/domain/board/query/application/service/FindBoardServiceTest.java
Labels: 📃 Docs, 🏗️ Refactoring

#114 [Closes #113] Feat : 게시물 상세 조회 구현
  src/main/java/com/spinetracker/spinetracker/domain/board/command/application/controller/BoardController.java
  src/main/java/com/spinetracker/spinetracker/domain/board/command/application/service/DeleteBoardService.java
  src/main/java/com/spinetracker/spinetracker/domain/board/query/application/controller/FindBoardController.java
  src/main/java/com/spinetracker/spinetracker/domain/board/query/application/dto/FindPostDTO.java
  src/main/java/com/spinetracker/spinetracker/domain/board/query/application/service/FindBoardService.java
  src/main/java/com/spinetracker/spinetracker/domain/board/query/domain/repository/BoardMapper.java
  src/main/resources/mapper/board/BoardMapper.xml
Labels: 📃 Docs, ✨ Feature
